/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mycode;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author darshana
 */
public class view_employee extends javax.swing.JInternalFrame {
    
    Connection Con = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
     String path = null;
     String imgpath;
     
     
     //int pos = 0;

    /** Creates new form view_employee */
    public view_employee() {
        initComponents();
        
        Con = DBconnect.Connect();
        tableload();
        IDautoIncrement();
         
    }
    
    public void IDautoIncrement(){
        try {
            Statement st = Con.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(id) FROM employee");
            rs.next();
            
            rs.getString("MAX(id)");
            
            if(rs.getString("MAX(id)") == null){
                
                EMPid.setText("EMP-00001");
                
            }else{
            
                long eid = Long.parseLong(rs.getString("MAX(id)").substring(4,rs.getString("MAX(id)").length()));
                eid++;
                EMPid.setText("EMP-"+String.format("%05d", eid));
               }
            } catch (Exception e) {
            }
    }
   
    public void tableload(){
    
        try {
            String sql = "select id,name,email,address,qualification,salary,age,tele from employee";
            pst = Con.prepareStatement(sql);
             rs=pst.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EMPid = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        eemail = new javax.swing.JTextField();
        eaddress = new javax.swing.JTextField();
        equalification = new javax.swing.JTextField();
        esalary = new javax.swing.JTextField();
        eage = new javax.swing.JTextField();
        etp = new javax.swing.JTextField();
        txt_path = new javax.swing.JLabel();
        ImageChooser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Search_name = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField9 = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Recipt = new javax.swing.JTextArea();
        Print = new javax.swing.JButton();
        Add_Record = new javax.swing.JButton();
        Search_id = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Mycode/Bundle"); // NOI18N
        setTitle(bundle.getString("view_employee.title")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(bundle.getString("view_employee.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText(bundle.getString("view_employee.jLabel2.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText(bundle.getString("view_employee.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText(bundle.getString("view_employee.jLabel5.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText(bundle.getString("view_employee.jLabel6.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText(bundle.getString("view_employee.jLabel7.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText(bundle.getString("view_employee.jLabel8.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(bundle.getString("view_employee.jLabel9.text")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText(bundle.getString("view_employee.jLabel10.text")); // NOI18N

        ImageChooser.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ImageChooser.setText(bundle.getString("view_employee.ImageChooser.text")); // NOI18N
        ImageChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageChooserActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1233, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        Search_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Search_name.setText(bundle.getString("view_employee.Search_name.text")); // NOI18N
        Search_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_nameActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Email", "Address", "Qualification", "Salary", "Age", "Telephone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Insert.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Insert.setText(bundle.getString("view_employee.Insert.text")); // NOI18N
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update.setText(bundle.getString("view_employee.Update.text")); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Delete.setText(bundle.getString("view_employee.Delete.text")); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Clear.setText(bundle.getString("view_employee.Clear.text")); // NOI18N
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Recipt.setColumns(20);
        Recipt.setRows(5);
        jScrollPane2.setViewportView(Recipt);

        Print.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Print.setText(bundle.getString("view_employee.Print.text")); // NOI18N
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        Add_Record.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_Record.setText(bundle.getString("view_employee.Add_Record.text")); // NOI18N
        Add_Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_RecordActionPerformed(evt);
            }
        });

        Search_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Search_id.setText(bundle.getString("view_employee.Search_id.text")); // NOI18N
        Search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(etp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(esalary, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equalification, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eemail, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EMPid, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageChooser)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(Search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(435, 435, 435)
                                    .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Add_Record, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(166, 166, 166)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Search_name)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EMPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(equalification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(esalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(etp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ImageChooser)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(Clear)
                    .addComponent(Add_Record)
                    .addComponent(Print))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImageChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageChooserActionPerformed
        // TODO add your handling code here:
        
        jFileChooser1.showOpenDialog(this);
        File f = jFileChooser1.getSelectedFile();
        String imgpath1=f.getAbsolutePath();
        imgpath = imgpath1.replace('\\','/');
        String path33 = f.getPath();
        if (f != null) {
            ImageIcon i = new ImageIcon(
                    new ImageIcon(f.getAbsolutePath()).
                    getImage().getScaledInstance(
                            txt_path.getWidth(), txt_path.getHeight(), Image.SCALE_SMOOTH));

            txt_path.setIcon(i);
        } else {
            txt_path.setText(null);
            txt_path.setIcon(new ImageIcon());
        }
    }
         public ImageIcon ResizedImage(String imgp){
        ImageIcon image=new ImageIcon(imgp);
        Image img=image.getImage();
        Image newImage=img.getScaledInstance(txt_path.getWidth(), txt_path.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imgeico=new ImageIcon(newImage);
        
        return imgeico;
        
       
    

    }//GEN-LAST:event_ImageChooserActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
      
        String id = EMPid.getText();
        String name = ename.getText();
        String email = eemail.getText();
        String address = eaddress.getText();
        String qualification = equalification.getText();
        String salary = esalary.getText();
        String age = eage.getText();
        String telephone = etp.getText();
        
        
        try {
             
            String sql = "INSERT INTO employee(id,name,email,address,qualification,salary,age,tele,image) values ('"+id+"','"+name+"','"+email+"','"+address+"','"+qualification+"','"+salary+"','"+age+"','"+telephone+"','"+imgpath+"')";
            pst = Con.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Insert Successfull");
            
            FileWriter writer=new FileWriter("Log-File.txt",true);
                writer.write(System.getProperty("line.separator"));
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
                writer.write(timeStamp+"----Employee name--"+ename.getText()+"----Insert from system");
                writer.close();
                
            tableload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }   
    }//GEN-LAST:event_InsertActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        
        int r = jTable1.getSelectedRow();
        
        String id = jTable1.getValueAt(r, 0).toString();
        String name = jTable1.getValueAt(r, 1).toString();
        String email = jTable1.getValueAt(r, 2).toString();
        String address = jTable1.getValueAt(r, 3).toString();
        String qualification = jTable1.getValueAt(r, 4).toString();
        String salary = jTable1.getValueAt(r, 5).toString();
        String age = jTable1.getValueAt(r, 6).toString();
        String tele = jTable1.getValueAt(r, 7).toString();
         String sql = "select * from employee where id='"+id+"'";
         try{
             pst = Con.prepareStatement(sql);
             rs=pst.executeQuery();
             if(rs.next()){
                 String img = rs.getString("image");
                 txt_path.setIcon(ResizedImage(img));
             }
             
             
         } catch (SQLException ex) {
             Logger.getLogger(Main_Page.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        EMPid.setText(id);
        ename.setText(name);
        eemail.setText(email);
        eaddress.setText(address);
        equalification.setText(qualification);
        esalary.setText(salary);
        eage.setText(age);
        etp.setText(tele);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
  
        int x =  JOptionPane.showConfirmDialog(null,"Do You want to update");
        
        if(x==0)
        {
        String id = EMPid.getText();
        String name = ename.getText();
        String email = eemail.getText();
        String address = eaddress.getText();
        String qualification = equalification.getText();
        String salary = esalary.getText();
        String age = eage.getText();
        String tele = etp.getText();
        
        String sql = "UPDATE employee SET id = '"+id+"',name ='"+name+"',email ='"+email+"',address ='"+address+"',qualification = '"+qualification+"',salary ='"+salary+"',age ='"+age+"',tele ='"+tele+"',image='"+imgpath+"' where id = '"+id+"'";
        
            try {
                
                pst = Con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"Update Successfull");
                
                FileWriter writer=new FileWriter("Log-File.txt",true);
                writer.write(System.getProperty("line.separator"));
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
                writer.write(timeStamp+"----Employee name--"+ename.getText()+"----Update from system");
                writer.close();
                
                tableload();
            } catch (Exception e) {
            }
        }
                // TODO add your handling code here:
       
        
        
       
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
      
        int x =  JOptionPane.showConfirmDialog(null,"Do You want to DELETE this");
        
        if(x==0)
        {
        String  id = EMPid.getText();
        String sql = "DELETE from employee where id ='"+ id +"'";
        
        try {
                
                pst = Con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"DELETE Successfull");
                
                FileWriter writer=new FileWriter("Log-File.txt",true);
                writer.write(System.getProperty("line.separator"));
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
                writer.write(timeStamp+"----Employee name--"+ename.getText()+"----Deleted from system");
                writer.close();
                
                tableload();
            } catch (Exception e) {
            }
        }
        
       
    }//GEN-LAST:event_DeleteActionPerformed

    private void Search_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_nameActionPerformed
        // TODO add your handling code here:
        
        String name = jTextField9.getText();
        
        String sql = "SELECT id,name,email,address,qualification,salary,age,tele FROM employee WHERE name LIKE '%"+ name +"%'";
        
        try {
            
            pst = Con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Search_nameActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
      
      EMPid.setText(null);
        ename.setText(null);
        eemail.setText(null);
        eaddress.setText(null);
        equalification.setText(null);
        esalary.setText(null);
        eage.setText(null);
        etp.setText(null);
        txt_path.setIcon(null);    
        
      
    }//GEN-LAST:event_ClearActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
           
            Recipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(view_employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void Add_RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_RecordActionPerformed
        
         Recipt.append("\t\t Employee Record\n\n"+
                
                "Employee Id:              \t\t\t"+EMPid.getText()+"\n\n"+
                "Employee Name:            \t\t\t"+ename.getText()+"\n\n"+
                "Employee Email:           \t\t\t"+eemail.getText()+"\n\n"+
                "Employee Address:         \t\t\t"+eaddress.getText()+"\n\n"+
                "Employee Qualification:   \t\t\t"+equalification.getText()+"\n\n"+
                "Employee Salary:          \t\t\t"+esalary.getText()+"\n\n"+
                "Employee Age:             \t\t\t"+eage.getText()+"\n\n"+
                "Employee Telephone No:    \t\t\t"+etp.getText()+"\n\n"
                 
        );
        
    }//GEN-LAST:event_Add_RecordActionPerformed

    private void Search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_idActionPerformed
        // TODO add your handling code here:
        
        String id = jTextField9.getText();
        
        String sql = "SELECT id,name,email,address,qualification,salary,age,tele FROM employee WHERE id LIKE '%"+ id +"%'";
        
        try {
            
            pst = Con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Search_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Record;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField EMPid;
    private javax.swing.JButton ImageChooser;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Print;
    private javax.swing.JTextArea Recipt;
    private javax.swing.JButton Search_id;
    private javax.swing.JButton Search_name;
    private javax.swing.JButton Update;
    private javax.swing.JTextField eaddress;
    private javax.swing.JTextField eage;
    private javax.swing.JTextField eemail;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField equalification;
    private javax.swing.JTextField esalary;
    private javax.swing.JTextField etp;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel txt_path;
    // End of variables declaration//GEN-END:variables

}
